// @ts-check
import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";
import tailwindcss from "@tailwindcss/vite";

// The public origin of the deployed site. Used for canonical URLs, the
// sitemap and the QR codes printed on memorial cards.
export const site = "https://librememorial.org";

const CONTENT_DIR = fileURLToPath(new URL("./src/content/memorials/", import.meta.url));

/**
 * Read the memorial visibility straight off disk: the sitemap is generated by
 * Astro before the content is loaded, and an unlisted memorial must never be
 * advertised here.
 */
function unlistedMemorialPaths() {
  const paths = new Set();
  let entries = [];
  try {
    entries = readdirSync(CONTENT_DIR, { withFileTypes: true });
  } catch {
    return paths;
  }
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    try {
      const raw = readFileSync(`${CONTENT_DIR}${entry.name}/memorial.json`, "utf8");
      if (JSON.parse(raw).visibility === "unlisted") paths.add(`/m/${entry.name}`);
    } catch {
      /* ignore unreadable memorials */
    }
  }
  return paths;
}

export default defineConfig({
  site,
  output: "static",
  trailingSlash: "never",
  // Emit `m/maria-popescu.html` rather than `m/maria-popescu/index.html`, so the
  // short URL printed on a QR card is served directly with no redirect.
  build: { format: "file" },
  integrations: [
    react(),
    sitemap({
      filter: (page) => {
        if (page.includes("/manage")) return false; // private editor
        if (page.endsWith("/create")) return false; // noindex landing for the form
        return ![...unlistedMemorialPaths()].some((path) => page.includes(path));
      },
    }),
  ],
  vite: {
    plugins: [tailwindcss()],
  },
});
